"""Keccak-f[1600]: classical reference and reversible quantum circuit.

State layout follows the standard: a 5x5 array of 64-bit lanes, indexed
``A[x][y]``, with lane bit ``z`` being bit ``z`` of the lane.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ..registers import CircuitBuilder, Word
from ..strategies import DEFAULT, Strategy

__all__ = [
    "KECCAK_ROTATION_OFFSETS",
    "KECCAK_ROUND_CONSTANTS",
    "KeccakCircuit",
    "build_keccak_f",
    "build_sha3",
    "chi_inverse_bit",
    "keccak_f",
    "sha3_256",
]

LANES = 5
LANE_BITS = 64
ROUNDS = 24


def _round_constants() -> tuple[int, ...]:
    """The 24 iota constants, generated by the LFSR the standard specifies.

    Derived rather than transcribed, in keeping with the SHA-2 constants.
    """
    constants = []
    lfsr = 1
    for _ in range(ROUNDS):
        constant = 0
        for j in range(7):
            lfsr, bit = ((lfsr << 1) ^ (0x71 if lfsr & 0x80 else 0)) & 0xFF, lfsr & 1
            if bit:
                constant ^= 1 << ((1 << j) - 1)
        constants.append(constant)
    return tuple(constants)


def _rotation_offsets() -> tuple[tuple[int, ...], ...]:
    """The rho offsets, generated by the standard's ``(x, y)`` walk."""
    offsets = [[0] * LANES for _ in range(LANES)]
    x, y = 1, 0
    for t in range(24):
        offsets[x][y] = ((t + 1) * (t + 2) // 2) % LANE_BITS
        x, y = y, (2 * x + 3 * y) % LANES
    return tuple(tuple(row) for row in offsets)


KECCAK_ROUND_CONSTANTS = _round_constants()
KECCAK_ROTATION_OFFSETS = _rotation_offsets()


# --------------------------------------------------------------------------
# Classical reference
# --------------------------------------------------------------------------


def _rotl(value: int, amount: int) -> int:
    amount %= LANE_BITS
    mask = (1 << LANE_BITS) - 1
    return ((value << amount) | (value >> (LANE_BITS - amount))) & mask


def keccak_f(state: list[list[int]], rounds: int = ROUNDS) -> list[list[int]]:
    """Keccak-f[1600], as the ground truth for the circuit.

    ``rounds`` is exposed for the same reason SHA-256's is: reduced-round
    variants are the scaling knob, and the circuit must be checkable at each.
    """
    a = [row[:] for row in state]
    mask = (1 << LANE_BITS) - 1
    for rnd in range(rounds):
        # theta
        c = [a[x][0] ^ a[x][1] ^ a[x][2] ^ a[x][3] ^ a[x][4] for x in range(LANES)]
        d = [c[(x - 1) % LANES] ^ _rotl(c[(x + 1) % LANES], 1) for x in range(LANES)]
        for x in range(LANES):
            for y in range(LANES):
                a[x][y] ^= d[x]
        # rho and pi
        b = [[0] * LANES for _ in range(LANES)]
        for x in range(LANES):
            for y in range(LANES):
                b[y][(2 * x + 3 * y) % LANES] = _rotl(a[x][y], KECCAK_ROTATION_OFFSETS[x][y])
        # chi
        for x in range(LANES):
            for y in range(LANES):
                a[x][y] = b[x][y] ^ ((~b[(x + 1) % LANES][y]) & b[(x + 2) % LANES][y] & mask)
        # iota
        a[0][0] ^= KECCAK_ROUND_CONSTANTS[rnd]
    return a


def sha3_256(message: bytes) -> bytes:
    """SHA3-256 via the sponge construction, for checking against hashlib."""
    rate = 136  # (1600 - 2*256) / 8
    padded = bytearray(message)
    padded.append(0x06)  # SHA-3 domain separation, then pad10*1
    while len(padded) % rate != 0:
        padded.append(0x00)
    # The trailing 1 bit shares the final byte when the domain byte already
    # sits there -- the classic 0x86 case, which a naive "append 0x80" gets
    # wrong for a message one byte short of the rate.
    padded[-1] |= 0x80

    state = [[0] * LANES for _ in range(LANES)]
    for offset in range(0, len(padded), rate):
        block = padded[offset : offset + rate]
        for i in range(rate // 8):
            lane = int.from_bytes(block[i * 8 : i * 8 + 8], "little")
            state[i % LANES][i // LANES] ^= lane
        state = keccak_f(state)

    out = bytearray()
    for i in range(4):  # 256 bits = 4 lanes
        out += state[i % LANES][i // LANES].to_bytes(8, "little")
    return bytes(out[:32])


def chi_inverse_bit(b: list[int], x: int) -> int:
    """``chi^-1`` for one row of five bits -- two ANDs deep, against chi's one."""
    n = LANES
    inner = b[(x + 2) % n] ^ ((~b[(x + 3) % n] & 1) & b[(x + 4) % n])
    return b[x] ^ ((~b[(x + 1) % n] & 1) & inner)


# --------------------------------------------------------------------------
# Quantum circuit
# --------------------------------------------------------------------------


@dataclass
class KeccakCircuit:
    builder: CircuitBuilder
    #: The lane holding the state on input, ``[x][y]``.
    state: list[list[Word]]
    #: The lane holding the state on output (ping-pong may swap the registers).
    output: list[list[Word]]
    rounds: int = ROUNDS
    scratch: list[list[Word]] = field(default_factory=list)
    #: theta's per-round scratch lanes, which this construction does not clear.
    theta_garbage: list[Word] = field(default_factory=list)

    @property
    def circuit(self):
        return self.builder.circuit


def _theta_inplace(b: CircuitBuilder, a: list[list[Word]], rnd: int) -> list[Word]:
    """Apply ``theta`` in place, returning the scratch lanes it could not clear.

    ``D[x] = C[x-1] XOR ROTL(C[x+1], 1)`` where ``C[x]`` is column ``x``'s
    parity.  Computing it is easy; *un*computing it is not, and the reason is
    worth recording because it is a genuine structural obstacle rather than an
    oversight.

    After the fold, column ``x`` has gained ``D[x]`` in all five of its lanes.
    Five is odd, so the column's parity changed by exactly ``D[x]``.  Recovering
    the original parities therefore needs ``D`` -- which is what we are trying to
    erase.  Writing the dependency out gives ``(I + M) D = v`` over GF(2), whose
    solution requires inverting a linear map on the whole 1600-bit state.  Every
    ordering of the obvious local moves runs into the same cycle, because
    ``D[x]`` depends on ``D[x-1]`` and ``D[x+1]`` around a 5-cycle.

    So this implementation **keeps** the scratch: 5 lanes (320 qubits) per round,
    7,680 qubits across the permutation.  That is the honest cost of the simple
    construction.  Closing it needs in-place CNOT-only synthesis of theta as an
    invertible GF(2) map -- which is what Amy et al. do, and it is why their
    circuit fits in 3,200 qubits while paying ~33 million CNOTs for the privilege.
    The tradeoff is recorded in the resource report rather than hidden.
    """
    from ..primitives.xor import xor_word

    def rotl1(word: Word) -> Word:
        return Word(word.bits[-1:] + word.bits[:-1], f"rotl1({word.label})")

    with b.section("theta"):
        d = [b.add_word(LANE_BITS, f"D{rnd}_{x}") for x in range(LANES)]
        for x in range(LANES):
            left, right = (x - 1) % LANES, (x + 1) % LANES
            for y in range(LANES):
                xor_word(b, a[left][y], d[x])
            for y in range(LANES):
                xor_word(b, rotl1(a[right][y]), d[x])
        for x in range(LANES):
            for y in range(LANES):
                xor_word(b, d[x], a[x][y])
    return d


def _rho_pi(a: list[list[Word]]) -> list[list[Word]]:
    """rho and pi together: pure rewiring, zero gates."""
    b: list[list[Word | None]] = [[None] * LANES for _ in range(LANES)]
    for x in range(LANES):
        for y in range(LANES):
            offset = KECCAK_ROTATION_OFFSETS[x][y] % LANE_BITS
            lane = a[x][y]
            # ROTL by `offset` on an LSB-first word.
            rotated = Word(
                lane.bits[-offset:] + lane.bits[:-offset] if offset else lane.bits,
                f"rho({lane.label})",
            )
            b[y][(2 * x + 3 * y) % LANES] = rotated
    return b  # type: ignore[return-value]


def _chi_into(
    b: CircuitBuilder, src: list[list[Word]], dst: list[list[Word]], use_gidney: bool
) -> None:
    """``dst = chi(src)`` with ``dst`` starting in ``|0>``.  One AND per bit."""
    from ..primitives.xor import xor_word

    with b.section("chi"):
        for y in range(LANES):
            for x in range(LANES):
                target = dst[x][y]
                xor_word(b, src[x][y], target)
                n1 = src[(x + 1) % LANES][y]
                n2 = src[(x + 2) % LANES][y]
                for z in range(LANE_BITS):
                    b.x(n1[z])
                    b.ccx(n1[z], n2[z], target[z])
                    b.x(n1[z])


def _chi_inverse_clear(
    b: CircuitBuilder, dst: list[list[Word]], src: list[list[Word]], use_gidney: bool
) -> None:
    """Clear ``src`` given ``dst = chi(src)``, using ``chi^-1``.

    ``chi^-1`` is two ANDs deep, which is the structural reason a reversible
    Keccak round costs roughly three times its forward AND count.
    """
    from ..primitives.xor import xor_word

    with b.section("chi inverse (clear source)"):
        for y in range(LANES):
            for x in range(LANES):
                target = src[x][y]
                b1 = dst[(x + 1) % LANES][y]
                b2 = dst[(x + 2) % LANES][y]
                b3 = dst[(x + 3) % LANES][y]
                b4 = dst[(x + 4) % LANES][y]
                with b.ancillas.borrow(LANE_BITS, "chi_inv_u") as u:
                    # u = B[x+2] XOR (NOT B[x+3] AND B[x+4])
                    # u starts |0>, so its AND may use Gidney's construction;
                    # the state lane below may not, since it is not clean.
                    for z in range(LANE_BITS):
                        b.x(b3[z])
                        if use_gidney:
                            b.and_g(b3[z], b4[z], u[z])
                        else:
                            b.ccx(b3[z], b4[z], u[z])
                        b.x(b3[z])
                    xor_word(b, b2, u)
                    # A[x] ^= B[x] XOR (NOT B[x+1] AND u)  ->  A[x] becomes 0
                    xor_word(b, dst[x][y], target)
                    for z in range(LANE_BITS):
                        b.x(b1[z])
                        b.ccx(b1[z], u[z], target[z])
                        b.x(b1[z])
                    # uncompute u: free under Gidney, since it is a
                    # measurement plus a Clifford correction.
                    xor_word(b, b2, u)
                    for z in range(LANE_BITS):
                        b.x(b3[z])
                        if use_gidney:
                            b.and_g_dg(b3[z], b4[z], u[z])
                        else:
                            b.ccx(b3[z], b4[z], u[z])
                        b.x(b3[z])


def _iota(b: CircuitBuilder, a: list[list[Word]], rnd: int) -> None:
    from ..primitives.xor import xor_const

    with b.section("iota"):
        xor_const(b, KECCAK_ROUND_CONSTANTS[rnd], a[0][0])


def build_keccak_f(
    rounds: int = ROUNDS,
    strategy: Strategy = DEFAULT,
    builder: CircuitBuilder | None = None,
    state: list[list[Word]] | None = None,
) -> KeccakCircuit:
    """Build a reversible Keccak-f[1600] over ``rounds`` rounds.

    Uses two 1600-qubit registers, ping-ponging: ``chi`` writes into the spare
    and ``chi^-1`` clears the source, so the spare becomes the state and the
    old state becomes the spare.  The swap itself is free -- it is a relabelling.
    """
    b = builder or CircuitBuilder(f"keccak_f_r{rounds}")
    if state is None:
        state = [[b.add_word(LANE_BITS, f"A{x}{y}") for y in range(LANES)] for x in range(LANES)]
    spare = [[b.add_word(LANE_BITS, f"B{x}{y}") for y in range(LANES)] for x in range(LANES)]

    current, other = state, spare
    garbage: list[Word] = []
    use_gidney = strategy.adder == "gidney"

    for rnd in range(rounds):
        with b.section(f"round[{rnd}]"):
            garbage.extend(_theta_inplace(b, current, rnd))
            permuted = _rho_pi(current)
            _chi_into(b, permuted, other, use_gidney)
            _chi_inverse_clear(b, other, permuted, use_gidney)
            _iota(b, other, rnd)
        current, other = other, current

    return KeccakCircuit(
        builder=b,
        state=state,
        output=current,
        rounds=rounds,
        scratch=other,
        theta_garbage=garbage,
    )


def build_sha3(rounds: int = ROUNDS, strategy: Strategy = DEFAULT) -> KeccakCircuit:
    """A single Keccak-f permutation, which is the whole cost of a SHA3 block."""
    return build_keccak_f(rounds, strategy)
